In [27]:
import numpy as np

A = np.array([[1,-2],[2,3]])
A

array([[ 1, -2],
       [ 2,  3]])

In [28]:
lambdas, V = np.linalg.eig(A)

In [29]:
lambdas

array([2.+1.73205081j, 2.-1.73205081j])

In [30]:
V

array([[-0.70710678+0.j        , -0.70710678-0.j        ],
       [ 0.35355339+0.61237244j,  0.35355339-0.61237244j]])

In [31]:
Vinv = np.linalg.inv(V)
Vinv

array([[-7.07106781e-01-0.40824829j,  0.00000000e+00-0.81649658j],
       [-7.07106781e-01+0.40824829j, -5.55111512e-17+0.81649658j]])

In [32]:
lambda_mat = np.diag(lambdas)
lambda_mat

array([[2.+1.73205081j, 0.+0.j        ],
       [0.+0.j        , 2.-1.73205081j]])

In [33]:
np.dot(V, np.dot(lambda_mat, Vinv))

array([[ 1.+2.72212288e-16j, -2.+7.37676565e-17j],
       [ 2.+1.90649975e-16j,  3.+1.57036409e-16j]])