# Eigen decomposition

## Example eigen decomposition with numpy
## Example eigen decomposition with pytorch

This is some plain text that forms a paragraph. Add emphasis via **bold** and __bold__, or *italic* and _italic_. 

Paragraphs must be separated by an empty line. 

* Sometimes we want to include lists. 
* Which can be bulleted using asterisks. 

1. Lists can also be numbered. 
2. If we want an ordered list.

[It is possible to include hyperlinks](https://www.example.com)

Inline code uses single backticks: foo(), and code blocks use triple backticks: 
```
bar()
``` 
Or can be indented by 4 spaces: 

    foo()

And finally, adding images is easy: ![Alt text](https://www.example.com/image.jpg)

In [1]:
import numpy as np
import torch as pt
import tensorflow as tf

## Example eigen decomposition with numpy

In [2]:
A = np.array([[-1, 3],[2, 1]])
A

array([[-1,  3],
       [ 2,  1]])

In [3]:
eigvalues,eigvectors = np.linalg.eig(A)
eigvalues

array([-2.64575131,  2.64575131])

In [4]:
eigvectors

array([[-0.8767397 , -0.6354064 ],
       [ 0.48096517, -0.7721779 ]])

In [5]:
v0 = eigvectors[:,0]
v0

array([-0.8767397 ,  0.48096517])

In [6]:
lambda_v0 = np.dot(eigvalues[0], v0)
lambda_v0

array([ 2.31963521, -1.27251423])

In [7]:
AxV0 = np.dot(A, v0)
AxV0

array([ 2.31963521, -1.27251423])

## Example eigen decomposition with pytorch

In [8]:
A_pt = pt.from_numpy(A).float()
A_pt

tensor([[-1.,  3.],
        [ 2.,  1.]])

In [9]:
lambdas_cplx, V_cplx = pt.linalg.eig(A_pt)

In [10]:
lambdas_cplx

tensor([-2.6458+0.j,  2.6458+0.j])

In [11]:
V_cplx

tensor([[-0.8767+0.j, -0.6354+0.j],
        [ 0.4810+0.j, -0.7722+0.j]])

In [12]:
V_float = V_cplx.float()
V_float

C:\Users\kumaraia\AppData\Local\Temp\ipykernel_299732\2181166141.py:1: UserWarning: Casting complex values to real discards the imaginary part (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\Copy.cpp:300.)
  V_float = V_cplx.float()


tensor([[-0.8767, -0.6354],
        [ 0.4810, -0.7722]])

In [13]:
pt.matmul(A_pt, V_float[:,0])

tensor([ 2.3196, -1.2725])

In [14]:
lambdas = lambdas_cplx.float()
lambdas

tensor([-2.6458,  2.6458])

In [15]:
lambda_0xV0 = lambdas[0]*V_float[:,0]
lambda_0xV0

tensor([ 2.3196, -1.2725])

## Example eigen decomposition with tensorflow

In [16]:
A_tf = tf.convert_to_tensor(A, dtype=tf.float32)
A_tf

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.,  3.],
       [ 2.,  1.]], dtype=float32)>

In [17]:
eigvalues, eigvectors = tf.linalg.eig(A_tf)

In [18]:
eigvalues

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([-2.6457515+0.j,  2.6457515+0.j], dtype=complex64)>

In [19]:
eigvectors

<tf.Tensor: shape=(2, 2), dtype=complex64, numpy=
array([[-0.87673974+0.j, -0.6354064 +0.j],
       [ 0.48096517+0.j, -0.7721779 +0.j]], dtype=complex64)>

In [20]:
lambda_0 = tf.cast(eigvalues[0],dtype=tf.float32)
lambda_1 = tf.cast(eigvalues[1],dtype = tf.float32)

In [21]:
lambda_0, lambda_1

(<tf.Tensor: shape=(), dtype=float32, numpy=-2.6457515>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.6457515>)

In [22]:
eigvec0 = tf.cast(eigvectors[:,0],dtype=tf.float32)
eigvec0

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.87673974,  0.48096517], dtype=float32)>

In [23]:
lambda_0xV0 = tf.multiply(lambda_0, eigvec0)
lambda_0xV0

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 2.3196354, -1.2725143], dtype=float32)>

In [24]:
AxV0 = tf.linalg.matvec(A_tf, eigvec0)
AxV0

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 2.3196354, -1.2725143], dtype=float32)>

## eigen values and eigne vectors for matrices when dimensions > 2

In [25]:
X = np.array([[25, 2, 9], [5, 26, -5], [3, 7, -1]])
X

array([[25,  2,  9],
       [ 5, 26, -5],
       [ 3,  7, -1]])

In [26]:
x_eigvalues, x_eigvec = np.linalg.eig(X)

In [27]:
x_eigvalues

array([29.67623202, 20.62117365, -0.29740567])

In [28]:
x_eigvec

array([[-0.71175736, -0.6501921 , -0.34220476],
       [-0.66652125,  0.74464056,  0.23789717],
       [-0.22170001,  0.15086635,  0.90901091]])

In [29]:
x_eigvec0 = x_eigvec[:,0]

In [30]:
x_eigvalues[0]*x_eigvec0

array([-21.12227645, -19.77983919,  -6.5792208 ])

In [31]:
np.matmul(X,x_eigvec0)

array([-21.12227645, -19.77983919,  -6.5792208 ])