# Moore Penrose Pseudo Inverse

## Example pseudoinverse with numpy
Pseudo inverse is defined by the following equation \
$A^{+} = VD^{+}U^{T}$ \
**where**: U, D and V are SVD of A. \
           $D^{+}$ is $D^{-1}$ with dimensions adjusted match $U^{T}$ to perform matrix multiplication

This is some plain text that forms a paragraph. Add emphasis via **bold** and __bold__, or *italic* and _italic_. 

Paragraphs must be separated by an empty line. 

* Sometimes we want to include lists. 
* Which can be bulleted using asterisks. 

1. Lists can also be numbered. 
2. If we want an ordered list.

[It is possible to include hyperlinks](https://www.example.com)

Inline code uses single backticks: foo(), and code blocks use triple backticks: 
```
bar()
``` 
Or can be indented by 4 spaces: 

    foo()

And finally, adding images is easy: ![Alt text](https://www.example.com/image.jpg)

In [25]:
import numpy as np
import torch

In [26]:
A = np.array([[-1, 2],[3, -2],[5,7]])

In [27]:
A

array([[-1,  2],
       [ 3, -2],
       [ 5,  7]])

In [28]:
U, D, VT = np.linalg.svd(A)

In [29]:
U

array([[ 0.12708324,  0.47409506,  0.87125411],
       [ 0.00164602, -0.87847553,  0.47778451],
       [ 0.99189069, -0.0592843 , -0.11241989]])

In [30]:
D

array([8.66918448, 4.10429538])

In [31]:
VT

array([[ 0.55798885,  0.82984845],
       [-0.82984845,  0.55798885]])

In [32]:
Dinv = np.linalg.inv(np.diag(D))
Dinv

array([[0.1153511 , 0.        ],
       [0.        , 0.24364718]])

In [33]:
Dplus = np.concatenate((Dinv, np.array([[0,0]]).T), axis=1)
Dplus

array([[0.1153511 , 0.        , 0.        ],
       [0.        , 0.24364718, 0.        ]])

In [34]:
Aplus = np.dot(VT.T, np.dot(Dplus, U.T))
Aplus

array([[-0.08767773,  0.17772512,  0.07582938],
       [ 0.07661927, -0.1192733 ,  0.08688784]])

In [35]:
np.linalg.pinv(A)

array([[-0.08767773,  0.17772512,  0.07582938],
       [ 0.07661927, -0.1192733 ,  0.08688784]])

# Moore penrose psuedo inverse with PyTorch

In [69]:
A_fpt = torch.from_numpy(A).float()
A_fpt

tensor([[-1.,  2.],
        [ 3., -2.],
        [ 5.,  7.]])

In [70]:
U_pt, D_pt, VT_pt = torch.linalg.svd(A_fpt)

In [71]:
U_pt

tensor([[ 0.1271,  0.4741,  0.8713],
        [ 0.0016, -0.8785,  0.4778],
        [ 0.9919, -0.0593, -0.1124]])

In [72]:
D_pt

tensor([8.6692, 4.1043])

In [73]:
VT_pt

tensor([[ 0.5580,  0.8298],
        [-0.8298,  0.5580]])

## Now calculate the pseudo inverse

In [74]:
D_pt_plus = torch.cat((torch.linalg.inv(torch.diag(D_pt)), torch.t(torch.tensor([[0,0]]))), dim=1)
D_pt_plus

tensor([[0.1154, 0.0000, 0.0000],
        [0.0000, 0.2436, 0.0000]])

In [76]:
A_pt_plus = torch.matmul(torch.t(VT_pt), torch.matmul(D_pt_plus, torch.t(U_pt)))
A_pt_plus

tensor([[-0.0877,  0.1777,  0.0758],
        [ 0.0766, -0.1193,  0.0869]])

In [78]:
torch.linalg.pinv(A_fpt)

tensor([[-0.0877,  0.1777,  0.0758],
        [ 0.0766, -0.1193,  0.0869]])