# Priciple Component  Analysis(PCA)
A tool to analyze the data set, gives the specified number of most important components from data. Like eigen decomposition and sigular value decomposition, PCA also performs a lossy compression of data

In [1]:
import torch as pt
import numpy as np

In [2]:
A = pt.tensor([[1,-2],[3, 1]], dtype=pt.float32)
A

tensor([[ 1., -2.],
        [ 3.,  1.]])

In [3]:
pt.t(A)

tensor([[ 1.,  3.],
        [-2.,  1.]])

In [4]:
pt.linalg.det(A)

tensor(7.)

In [5]:
pt.linalg.inv(A)

tensor([[ 0.1429,  0.2857],
        [-0.4286,  0.1429]])

In [25]:
U, Sigma, Vt =  pt.svd(A)
U

tensor([[-0.1891, -0.9820],
        [-0.9820,  0.1891]])

In [26]:
Sigma

tensor([3.1926, 2.1926])

In [27]:
Vt

tensor([[-0.9820, -0.1891],
        [-0.1891,  0.9820]])

In [28]:
pt.matmul(U, pt.matmul(pt.diag(Sigma), Vt))
# pt.diag(Sigma)

tensor([[ 1.0000, -2.0000],
        [ 3.0000,  1.0000]])