## Sigular value decomposition example

In [4]:
import numpy as np

In [5]:
A = np.array([[-1,2],[3, -2],[5, 7]])

In [6]:
U, S, VT = np.linalg.svd(A)

In [7]:
U

array([[ 0.12708324,  0.47409506,  0.87125411],
       [ 0.00164602, -0.87847553,  0.47778451],
       [ 0.99189069, -0.0592843 , -0.11241989]])

In [8]:
S

array([8.66918448, 4.10429538])

In [9]:
VT

array([[ 0.55798885,  0.82984845],
       [-0.82984845,  0.55798885]])

In [10]:
V = np.transpose(VT)
V

array([[ 0.55798885, -0.82984845],
       [ 0.82984845,  0.55798885]])

In [11]:
Smat = np.concatenate((np.diag(S), [[0,0]]), axis=0)
Smat

array([[8.66918448, 0.        ],
       [0.        , 4.10429538],
       [0.        , 0.        ]])

In [12]:
np.dot(U, np.dot(Smat, VT))

array([[-1.,  2.],
       [ 3., -2.],
       [ 5.,  7.]])

In [14]:
U[:,:1] # meaning all rows but only one one column

array([[0.12708324],
       [0.00164602],
       [0.99189069]])

In [20]:
A_approx = np.dot(U, np.dot([[S[0]]], VT[:1, :]))
A_approx

array([[0.6147408 , 0.91425071],
       [0.00796231, 0.01184165],
       [4.79808104, 7.13577001]])

In [21]:
np.dot(S[1], A_approx)

array([[ 2.52307784,  3.75235495],
       [ 0.03267967,  0.04860164],
       [19.69274183, 29.28730783]])